# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
warnings_are_errors: true
r_build_args: --resave-data --compact-vignettes=gs+qpdf
r_github_packages:
  - jimhester/covr
  - kbenoit/quanteda
after_success:
  - Rscript -e 'library(covr);codecov()'
